# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_auto_20190417_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='pf_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('idy', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('x', models.TextField()),
                ('y', models.TextField()),
                ('pf_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pf_inst2',
            name='pf_user',
        ),
        migrations.DeleteModel(
            name='pf_inst2',
        ),
    ]
