# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='meta',
        ),
    ]
